//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petitPateLib.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cinema
    {
        public Cinema()
        {
            this.Projection = new HashSet<Projection>();
        }
    
        public int IdCinema { get; set; }
        public string Name { get; set; }
        public int Nb_Places { get; set; }
        public int Emplacement { get; set; }
    
        public virtual Emplacement Emplacement1 { get; set; }
        public virtual ICollection<Projection> Projection { get; set; }
    }
}
