//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petitPateLib.Logic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class petitPateBDDEntities : DbContext
    {
        public petitPateBDDEntities()
            : base("name=petitPateBDDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cinema> Cinema { get; set; }
        public DbSet<Emplacement> Emplacement { get; set; }
        public DbSet<Movie> Movie { get; set; }
        public DbSet<Movie_category> Movie_category { get; set; }
        public DbSet<Projection> Projection { get; set; }
        public DbSet<Reservation> Reservation { get; set; }
        public DbSet<UserTable> UserTable { get; set; }
    }
}
