//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petitPateLib.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public Movie()
        {
            this.Projection = new HashSet<Projection>();
        }
    
        public int IdFilm { get; set; }
        public string Title { get; set; }
        public string Synopsis { get; set; }
        public string Producer { get; set; }
        public byte[] Poster { get; set; }
        public int Category { get; set; }
    
        public virtual Movie_category Movie_category { get; set; }
        public virtual ICollection<Projection> Projection { get; set; }
    }
}
