//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petitPateLib.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie_category
    {
        public Movie_category()
        {
            this.Movie = new HashSet<Movie>();
        }
    
        public int IdMovieCategory { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Movie> Movie { get; set; }
    }
}
