//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petitPateLib.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projection
    {
        public Projection()
        {
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int IdProjectiondatetime { get; set; }
        public string LangVersion { get; set; }
        public int MovieId { get; set; }
        public int CinemaId { get; set; }
        public System.DateTime DateHeure { get; set; }
    
        public virtual Cinema Cinema { get; set; }
        public virtual Movie Movie { get; set; }
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
