//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petitPateLib.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int IdReservation { get; set; }
        public int nbPlaces { get; set; }
        public int Projection { get; set; }
        public int UserId { get; set; }
    
        public virtual Projection Projection1 { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
